language: cpp
compiler:
  - clang
  - gcc
cache:
  directories:
    - external
install:
  - cd external
  - timeout 60 make || true
script:
  - mkdir build
  - cd build
  - cmake .. && make && make check
