language: cpp
compiler:
  - clang
  - gcc
env:
  - TSUGU_BUILD_TYPE=Debug
  - TSUGU_BUILD_TYPE=Release
cache:
  directories:
    - external
install:
  - cd ${TRAVIS_BUILD_DIR}/external
  - timeout 1800 make || true
script:
  - mkdir ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake -DCMAKE_BUILD_TYPE=${TSUGU_BUILD_TYPE} .. && make && make check
