language: cpp
compiler:
  - clang
  - gcc
cache:
  directories:
    - external
install:
  - cd ${TRAVIS_BUILD_DIR}/external
  - timeout 2400 make || true
script:
  - mkdir ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake -DCMAKE_BUILD_TYPE=Release .. && make && make check
