language: cpp
compiler:
  - clang
  - gcc
cache:
  directories:
    - external
install:
  - cd ${TRAVIS_BUILD_DIR}/external
  - timeout 1800 make || true
script:
  - mkdir ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake .. && make && make check
